In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [2]:
nba_training_df = pd.read_csv('data/training_games4.csv')
nba_training_df.head()

,game_id,game_date,home_team,away_team,away_FGM,away_FGA,away_FG_PCT,away_FG3M,away_FG3A,away_FG3_PCT,...,home_10g_player_BLK,away_10g_player_TO,home_10g_player_TO,away_10g_player_PF,home_10g_player_PF,away_10g_player_PTS,home_10g_player_PTS,away_10g_player_PLUS_MINUS,home_10g_player_PLUS_MINUS,score_diff
0,20000058,2000-11-07,HOU,LAL,34.959581,80.359116,0.434748,4.869439,14.495202,0.332994,...,0.458521,1.713223,1.612160,2.490622,2.672306,15.149697,11.308576,5.335229,1.380674,10
1,20000060,2000-11-07,POR,ATL,33.588252,79.188427,0.426121,4.781623,12.173597,0.358209,...,0.850657,2.501213,2.123538,3.193895,2.929524,11.575277,10.350852,-7.701101,-4.093827,-9
2,20000067,2000-11-08,DAL,MEM,34.512358,81.973248,0.422038,4.821751,13.433265,0.365002,...,0.553944,1.860208,1.390167,2.562125,2.579181,10.837868,10.873075,1.062694,3.413240,-27
3,20000070,2000-11-08,LAC,UTA,34.840361,71.230300,0.492003,4.290782,10.778424,0.423109,...,0.507130,1.610283,1.451214,2.825818,2.432686,12.436075,8.693520,4.559189,-2.760369,-6
4,20000069,2000-11-08,DEN,MIN,38.792382,79.389939,0.489491,4.133178,9.077930,0.450685,...,0.737421,1.797572,1.962515,3.429119,3.099911,13.172195,11.273352,-0.934327,-2.911181,2

In [3]:
nba_training_df.drop(columns=['game_id', 'game_date', 'home_team', 'away_team'])

,away_FGM,away_FGA,away_FG_PCT,away_FG3M,away_FG3A,away_FG3_PCT,away_FTM,away_FTA,away_FT_PCT,away_OREB,...,home_10g_player_BLK,away_10g_player_TO,home_10g_player_TO,away_10g_player_PF,home_10g_player_PF,away_10g_player_PTS,home_10g_player_PTS,away_10g_player_PLUS_MINUS,home_10g_player_PLUS_MINUS,score_diff
0,34.959581,80.359116,0.434748,4.869439,14.495202,0.332994,18.353010,26.665891,0.715747,9.949695,...,0.458521,1.713223,1.612160,2.490622,2.672306,15.149697,11.308576,5.335229,1.380674,10
1,33.588252,79.188427,0.426121,4.781623,12.173597,0.358209,22.987496,30.653969,0.765498,12.892992,...,0.850657,2.501213,2.123538,3.193895,2.929524,11.575277,10.350852,-7.701101,-4.093827,-9
2,34.512358,81.973248,0.422038,4.821751,13.433265,0.365002,19.070660,25.905205,0.747131,14.360570,...,0.553944,1.860208,1.390167,2.562125,2.579181,10.837868,10.873075,1.062694,3.413240,-27
3,34.840361,71.230300,0.492003,4.290782,10.778424,0.423109,24.864205,34.273335,0.740992,9.135795,...,0.507130,1.610283,1.451214,2.825818,2.432686,12.436075,8.693520,4.559189,-2.760369,-6
4,38.792382,79.389939,0.489491,4.133178,9.077930,0.450685,19.417272,23.601047,0.817003,10.551614,...,0.737421,1.797572,1.962515,3.429119,3.099911,13.172195,11.273352,-0.934327,-2.911181,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28424,43.744369,89.922802,0.487091,14.912105,38.570517,0.384897,16.648004,20.492148,0.814381,11.759454,...,0.418417,0.909154,1.069743,1.185092,2.104986,7.591998,12.896681,-4.949684,-0.381736,11
28425,42.312702,89.186266,0.474237,14.945429,39.671717,0.376750,16.152144,20.566360,0.777310,10.702600,...,0.562431,0.223653,1.773535,0.592069,2.159653,2.634257,10.066896,1.017049,-4.574694,28
28426,40.990112,89.219725,0.461296,15.759751,41.961415,0.379907,16.724823,21.409535,0.782045,10.115478,...,0.232437,0.755472,1.864465,1.199131,1.902340,8.241198,13.685674,5.866606,-13.591576,-15
28427,44.896218,92.328958,0.486737,15.186275,39.293505,0.384314,17.414996,21.819514,0.796238,11.317145,...,0.671965,1.246133,1.881625,1.417850,2.226479,10.598373,13.898778,2.563624,-2.816937,-20
28428,40.998956,87.055264,0.472630,12.817513,34.003680,0.378408,16.104522,20.173890,0.800528,10.783204,...,0.188111,0.438278,1.525097,1.298308,2.064882,5.320271,12.335757,-1.031987,-6.212910,-8

In [4]:
nba_training_df = nba_training_df[nba_training_df['score_diff'] != 0]
nba_training_df['outcome'] = nba_training_df['score_diff'].apply(lambda x: 1 if x > 0 else 0)

y1 = nba_training_df['outcome']
y2 = nba_training_df['score_diff']
X1 = nba_training_df.drop(columns=['outcome', 'score_diff'])
X2 = nba_training_df.drop(columns=['outcome', 'score_diff'])

X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=42)
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.2, random_state=42)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, cross_validate, KFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report, confusion_matrix
import numpy as np

# Initialize scaler for feature normalization
scaler = StandardScaler()

# Fit and transform the features
X1_scaled = scaler.fit_transform(X1)

print(f"Dataset shape: {X1_scaled.shape}")
print(f"Number of features: {X1_scaled.shape[1]}")
print(f"Number of samples: {X1_scaled.shape[0]}")
print(f"\nTarget distribution:")
print(y1.value_counts())
print(f"Positive class rate: {y1.mean():.4f}")

Dataset shape: (28429, 116)
Number of features: 116
Number of samples: 28429

Target distribution:
outcome
1    14380
0    14049
Name: count, dtype: int64
Positive class rate: 0.5058

In [7]:
# Initialize Logistic Regression model
log_reg = LogisticRegression(
    max_iter=1000,
    random_state=42,
    solver='lbfgs',
    class_weight='balanced'  # Handle any class imbalance
)

# Set up K-Fold cross-validation (k=5)
k_folds = 5
kf = KFold(n_splits=k_folds, shuffle=True, random_state=42)

# Define scoring metrics
scoring = {
    'accuracy': 'accuracy',
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1',
    'roc_auc': 'roc_auc'
}

print(f"Performing {k_folds}-Fold Cross-Validation...")
print(f"{'='*60}\n")

# Perform cross-validation
cv_results = cross_validate(
    log_reg, 
    X1_scaled, 
    y1, 
    cv=kf, 
    scoring=scoring,
    return_train_score=True,
    n_jobs=-1  # Use all available cores
)

# Display results
print("Cross-Validation Results:")
print(f"{'='*60}")
print(f"\nTest Set Performance (mean ± std across {k_folds} folds):")
print(f"  Accuracy:  {cv_results['test_accuracy'].mean():.4f} ± {cv_results['test_accuracy'].std():.4f}")
print(f"  Precision: {cv_results['test_precision'].mean():.4f} ± {cv_results['test_precision'].std():.4f}")
print(f"  Recall:    {cv_results['test_recall'].mean():.4f} ± {cv_results['test_recall'].std():.4f}")
print(f"  F1 Score:  {cv_results['test_f1'].mean():.4f} ± {cv_results['test_f1'].std():.4f}")
print(f"  ROC AUC:   {cv_results['test_roc_auc'].mean():.4f} ± {cv_results['test_roc_auc'].std():.4f}")

print(f"\nTraining Set Performance (mean ± std across {k_folds} folds):")
print(f"  Accuracy:  {cv_results['train_accuracy'].mean():.4f} ± {cv_results['train_accuracy'].std():.4f}")
print(f"  Precision: {cv_results['train_precision'].mean():.4f} ± {cv_results['train_precision'].std():.4f}")
print(f"  Recall:    {cv_results['train_recall'].mean():.4f} ± {cv_results['train_recall'].std():.4f}")
print(f"  F1 Score:  {cv_results['train_f1'].mean():.4f} ± {cv_results['train_f1'].std():.4f}")
print(f"  ROC AUC:   {cv_results['train_roc_auc'].mean():.4f} ± {cv_results['train_roc_auc'].std():.4f}")

# Check for overfitting
print(f"\nOverfitting Check:")
train_test_gap = cv_results['train_accuracy'].mean() - cv_results['test_accuracy'].mean()
print(f"  Train-Test Accuracy Gap: {train_test_gap:.4f}")
if train_test_gap > 0.05:
    print("  ⚠️  Warning: Possible overfitting detected")
else:
    print("  ✓ Model generalizes well")

print(f"\n{'='*60}")

Performing 5-Fold Cross-Validation...
============================================================

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Cross-Validation Results:
============================================================

Test Set Performance (mean ± std across 5 folds):
  Accuracy:  0.7847 ± 0.0053
  Precision: 0.7891 ± 0.0061
  Recall:    0.7839 ± 0.0068
  F1 Score:  0.7865 ± 0.0052
  ROC AUC:   0.8753 ± 0.0053

Training Set Performance (mean ± std across 5 folds):
  Accuracy:  0.7879 ± 0.0018
  Precision: 0.7923 ± 0.0020
  Recall:    0.7868 ± 0.0012
  F1 Score:  0.7896 ± 0.0016
  ROC AUC:   0.8783 ± 0.0014

Overfitting Check:
  Train-Test Accuracy Gap: 0.0032
  ✓ Model generalizes well

============================================================

In [8]:
# Train final model on all data and examine feature importance
print("Training final model on full dataset...")
log_reg_final = LogisticRegression(
    max_iter=1000,
    random_state=42,
    solver='lbfgs',
    class_weight='balanced'
)

log_reg_final.fit(X1_scaled, y1)

# Get feature importance (coefficients)
feature_importance = pd.DataFrame({
    'feature': X1.columns,
    'coefficient': log_reg_final.coef_[0],
    'abs_coefficient': np.abs(log_reg_final.coef_[0])
})

# Sort by absolute value
feature_importance = feature_importance.sort_values('abs_coefficient', ascending=False)

print(f"\nTop 20 Most Important Features:")
print(f"{'='*60}")
print(feature_importance.head(20).to_string(index=False))

print(f"\n\nModel Intercept: {log_reg_final.intercept_[0]:.4f}")
print(f"\n✓ Model training complete!")

Training final model on full dataset...

Top 20 Most Important Features:
============================================================
            feature  coefficient  abs_coefficient
           away_eFG    -2.616973         2.616973
           home_eFG     2.245565         2.245565
home_10g_player_FTA     0.340731         0.340731
home_10g_player_FTM    -0.318258         0.318258
           away_FTM    -0.204476         0.204476
          home_FG3A     0.200538         0.200538
           away_FTA     0.200227         0.200227
 home_5g_player_FTA    -0.198163         0.198163
 home_5g_player_FTM     0.194185         0.194185
 away_5g_player_FTM     0.158646         0.158646
 away_5g_player_FTA    -0.152744         0.152744
        away_losses     0.148624         0.148624
          home_FG3M    -0.134382         0.134382
           home_FTA     0.132319         0.132319
        home_losses    -0.125447         0.125447
          away_FG3M     0.103278         0.103278
           home_FTM    -0.102986         0.102986
          away_wins    -0.099979         0.099979
          home_wins     0.097565         0.097565
away_10g_player_FGA     0.096435         0.096435


Model Intercept: 0.0170

✓ Model training complete!

In [9]:
# Detailed fold-by-fold analysis
print("Fold-by-Fold Performance:")
print(f"{'='*60}\n")

for fold_idx in range(k_folds):
    print(f"Fold {fold_idx + 1}:")
    print(f"  Test Accuracy:  {cv_results['test_accuracy'][fold_idx]:.4f}")
    print(f"  Test Precision: {cv_results['test_precision'][fold_idx]:.4f}")
    print(f"  Test Recall:    {cv_results['test_recall'][fold_idx]:.4f}")
    print(f"  Test F1:        {cv_results['test_f1'][fold_idx]:.4f}")
    print(f"  Test ROC AUC:   {cv_results['test_roc_auc'][fold_idx]:.4f}")
    print()

# Create a summary DataFrame
fold_summary = pd.DataFrame({
    'Fold': range(1, k_folds + 1),
    'Accuracy': cv_results['test_accuracy'],
    'Precision': cv_results['test_precision'],
    'Recall': cv_results['test_recall'],
    'F1': cv_results['test_f1'],
    'ROC_AUC': cv_results['test_roc_auc']
})

print("\nSummary Table:")
print(fold_summary.to_string(index=False))

Fold-by-Fold Performance:
============================================================

Fold 1:
  Test Accuracy:  0.7807
  Test Precision: 0.7847
  Test Recall:    0.7812
  Test F1:        0.7829
  Test ROC AUC:   0.8738

Fold 2:
  Test Accuracy:  0.7833
  Test Precision: 0.7847
  Test Recall:    0.7858
  Test F1:        0.7852
  Test ROC AUC:   0.8732

Fold 3:
  Test Accuracy:  0.7849
  Test Precision: 0.7871
  Test Recall:    0.7912
  Test F1:        0.7892
  Test ROC AUC:   0.8718

Fold 4:
  Test Accuracy:  0.7798
  Test Precision: 0.7880
  Test Recall:    0.7721
  Test F1:        0.7800
  Test ROC AUC:   0.8720

Fold 5:
  Test Accuracy:  0.7947
  Test Precision: 0.8011
  Test Recall:    0.7891
  Test F1:        0.7950
  Test ROC AUC:   0.8859


Summary Table:
 Fold  Accuracy  Precision   Recall       F1  ROC_AUC
    1  0.780689   0.784717 0.781174 0.782942 0.873783
    2  0.783327   0.784669 0.785764 0.785216 0.873177
    3  0.784910   0.787139 0.791220 0.789174 0.871818
    4  0.779810   0.787997 0.772095 0.779965 0.871977
    5  0.794723   0.801062 0.789052 0.795011 0.885925

In [10]:
# ============================================================
# Additional Models: Decision Tree, XGBoost, and Basic Neural Net
# ============================================================

from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import make_scorer

# (Optional) XGBoost
# If you don't have xgboost installed, uncomment the next line:
# !pip -q install xgboost
try:
    from xgboost import XGBClassifier
    _HAS_XGBOOST = True
except Exception as e:
    print("⚠️  xgboost not available in this environment. Install with: pip install xgboost")
    _HAS_XGBOOST = False

# We'll compare using the same CV splitter and scoring dict you already set up:
print(f"Using {k_folds}-fold CV with scoring: {list(scoring.keys())}")

Using 5-fold CV with scoring: ['accuracy', 'precision', 'recall', 'f1', 'roc_auc']

In [11]:
# Build model zoo
pos_rate = float(y1.mean())
neg_rate = 1.0 - pos_rate
# XGBoost's typical imbalance parameter (approx)
scale_pos_weight = (neg_rate / pos_rate) if pos_rate > 0 else 1.0

models = {}

# 1) Decision Tree (simple, interpretable baseline)
models["DecisionTree"] = DecisionTreeClassifier(
    random_state=42,
    class_weight="balanced",
    max_depth=None  # you can tune this later
)

# 2) XGBoost (strong baseline for tabular data)
if _HAS_XGBOOST:
    models["XGBoost"] = XGBClassifier(
        n_estimators=600,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.9,
        colsample_bytree=0.9,
        reg_lambda=1.0,
        random_state=42,
        n_jobs=-1,
        eval_metric="logloss",
        scale_pos_weight=scale_pos_weight
    )

# 3) Basic Neural Net (MLP) — use a pipeline with scaling
models["MLP"] = Pipeline([
    ("scaler", StandardScaler()),
    ("mlp", MLPClassifier(
        hidden_layer_sizes=(128, 64),
        activation="relu",
        solver="adam",
        alpha=1e-4,
        batch_size=256,
        learning_rate_init=1e-3,
        max_iter=200,
        early_stopping=True,
        n_iter_no_change=10,
        random_state=42
    ))
])

# Evaluate each model with cross_validate
results = []
for name, model in models.items():
    print(f"\n{name}")
    print("-" * len(name))
    # NOTE:
    # - For Logistic Regression earlier you used X1_scaled.
    # - For tree/XGBoost, scaling isn't required, but it's fine to use raw X1.
    # - For MLP we embedded scaling into the pipeline, so use raw X1.
    cv = cross_validate(
        model,
        X1,      # raw features
        y1,
        cv=kf,
        scoring=scoring,
        return_train_score=True,
        n_jobs=-1
    )
    results.append({
        "model": name,
        "test_accuracy_mean": cv["test_accuracy"].mean(),
        "test_accuracy_std":  cv["test_accuracy"].std(),
        "test_precision_mean": cv["test_precision"].mean(),
        "test_precision_std":  cv["test_precision"].std(),
        "test_recall_mean": cv["test_recall"].mean(),
        "test_recall_std":  cv["test_recall"].std(),
        "test_f1_mean": cv["test_f1"].mean(),
        "test_f1_std":  cv["test_f1"].std(),
        "test_roc_auc_mean": cv["test_roc_auc"].mean(),
        "test_roc_auc_std":  cv["test_roc_auc"].std(),
        "train_accuracy_mean": cv["train_accuracy"].mean(),
        "train_accuracy_std":  cv["train_accuracy"].std(),
        "train_roc_auc_mean": cv["train_roc_auc"].mean(),
        "train_roc_auc_std":  cv["train_roc_auc"].std(),
        "train_test_acc_gap": cv["train_accuracy"].mean() - cv["test_accuracy"].mean(),
    })

results_df = pd.DataFrame(results)

# Rank by ROC AUC (usually good for probabilistic win/loss classification)
results_df = results_df.sort_values(by="test_roc_auc_mean", ascending=False)

# Pretty print
cols = [
    "model",
    "test_roc_auc_mean","test_roc_auc_std",
    "test_accuracy_mean","test_accuracy_std",
    "test_f1_mean","test_f1_std",
    "test_precision_mean","test_precision_std",
    "test_recall_mean","test_recall_std",
    "train_test_acc_gap"
]
display(results_df[cols].style.format({
    "test_roc_auc_mean":"{:.4f}","test_roc_auc_std":"{:.4f}",
    "test_accuracy_mean":"{:.4f}","test_accuracy_std":"{:.4f}",
    "test_f1_mean":"{:.4f}","test_f1_std":"{:.4f}",
    "test_precision_mean":"{:.4f}","test_precision_std":"{:.4f}",
    "test_recall_mean":"{:.4f}","test_recall_std":"{:.4f}",
    "train_test_acc_gap":"{:.4f}",
}))

DecisionTree
------------

XGBoost
-------

MLP
---

In [12]:
# Train the best-performing model on all data (by ROC AUC) and report a quick holdout metric too
best_name = results_df.iloc[0]["model"]
best_model = models[best_name]

print(f"Best model by CV ROC AUC: {best_name}")

# Holdout evaluation (same split you created earlier: X1_train/X1_test)
best_model.fit(X1_train, y1_train)

# Predict probabilities if available; else fallback
if hasattr(best_model, "predict_proba"):
    y_proba = best_model.predict_proba(X1_test)[:, 1]
    y_pred = (y_proba >= 0.5).astype(int)
else:
    y_pred = best_model.predict(X1_test)
    y_proba = None

from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, precision_score, recall_score

print("\nHoldout Performance (20% split):")
print(f"  Accuracy : {accuracy_score(y1_test, y_pred):.4f}")
print(f"  Precision: {precision_score(y1_test, y_pred):.4f}")
print(f"  Recall   : {recall_score(y1_test, y_pred):.4f}")
print(f"  F1       : {f1_score(y1_test, y_pred):.4f}")
if y_proba is not None:
    print(f"  ROC AUC   : {roc_auc_score(y1_test, y_proba):.4f}")
else:
    print("  ROC AUC   : (no predict_proba available)")

# Feature importance for tree/XGBoost models (if supported)
if best_name in ["DecisionTree", "XGBoost"]:
    if best_name == "DecisionTree":
        importances = best_model.feature_importances_
    else:
        # XGBClassifier exposes feature_importances_
        importances = best_model.feature_importances_

    fi = pd.DataFrame({"feature": X1.columns, "importance": importances}).sort_values("importance", ascending=False)
    print("\nTop 25 Feature Importances:")
    display(fi.head(25))

Best model by CV ROC AUC: XGBoost

Holdout Performance (20% split):
  Accuracy : 0.7800
  Precision: 0.7819
  Recall   : 0.7843
  F1       : 0.7831
  ROC AUC   : 0.8720

Top 25 Feature Importances:

                        feature  importance
43                     home_eFG    0.079420
42                     away_eFG    0.071784
23                    home_FG3A    0.018853
4                     away_FG3A    0.014382
36                     home_PTS    0.013439
81          home_10g_player_FGA    0.010134
19                     home_FGM    0.009740
22                    home_FG3M    0.009180
48          away_5g_player_FG3M    0.008430
12                     away_AST    0.008362
50          away_5g_player_FG3A    0.008349
94       away_10g_player_FT_PCT    0.008290
41                  away_losses    0.008247
112         away_10g_player_PTS    0.008240
38                    home_wins    0.008221
35                      home_PF    0.008213
80          away_10g_player_FGA    0.008131
84         away_10g_player_FG3M    0.008006
1                      away_FGA    0.008003
10                    away_DREB    0.007945
21                  home_FG_PCT    0.007944
26                     home_FTA    0.007826
115  home_10g_player_PLUS_MINUS    0.007786
14                     away_BLK    0.007776
85         home_10g_player_FG3M    0.007728

In [14]:
# XGBoost Hyperparameter Grid Search
print("="*60)
print("XGBoost Hyperparameter Grid Search")
print("="*60)

from sklearn.model_selection import GridSearchCV
import xgboost as xgb

# Define parameter grid for XGBoost
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7, 10],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'min_child_weight': [1, 3, 5],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'gamma': [0, 0.1, 0.2]
}

print(f"\nParameter grid:")
for param, values in param_grid.items():
    print(f"  {param}: {values}")

print(f"\nTotal combinations: {np.prod([len(v) for v in param_grid.values()])}")

# Initialize XGBoost classifier
xgb_clf = xgb.XGBClassifier(
    objective='binary:logistic',
    eval_metric='logloss',
    random_state=42,
    n_jobs=-1
)

# Initialize GridSearchCV
grid_search = GridSearchCV(
    estimator=xgb_clf,
    param_grid=param_grid,
    scoring='roc_auc',
    cv=5,
    verbose=2,
    n_jobs=-1,
    return_train_score=True
)

print("\nStarting grid search (this may take a while)...")
print("Using 5-fold cross-validation with ROC AUC scoring\n")

# Fit grid search
grid_search.fit(X1_train, y1_train)

print("\n" + "="*60)
print("Grid Search Complete!")
print("="*60)

# Best parameters
print("\nBest Parameters:")
for param, value in grid_search.best_params_.items():
    print(f"  {param}: {value}")

print(f"\nBest CV ROC AUC Score: {grid_search.best_score_:.4f}")

# Test on holdout set with best model
best_xgb = grid_search.best_estimator_
y_pred_best = best_xgb.predict(X1_test)
y_proba_best = best_xgb.predict_proba(X1_test)[:, 1]

print("\nHoldout Performance (Best XGBoost):")
print(f"  Accuracy : {accuracy_score(y1_test, y_pred_best):.4f}")
print(f"  Precision: {precision_score(y1_test, y_pred_best):.4f}")
print(f"  Recall   : {recall_score(y1_test, y_pred_best):.4f}")
print(f"  F1       : {f1_score(y1_test, y_pred_best):.4f}")
print(f"  ROC AUC   : {roc_auc_score(y1_test, y_proba_best):.4f}")

# Feature importance
importances_best = best_xgb.feature_importances_
fi_best = pd.DataFrame({
    "feature": X1.columns, 
    "importance": importances_best
}).sort_values("importance", ascending=False)

print("\nTop 25 Feature Importances (Best Model):")
display(fi_best.head(25))

# Show top 10 parameter combinations
print("\nTop 10 Parameter Combinations by CV Score:")
results_df = pd.DataFrame(grid_search.cv_results_)
results_df = results_df.sort_values('mean_test_score', ascending=False)
display(results_df[['params', 'mean_test_score', 'std_test_score', 'mean_train_score']].head(10))

============================================================
XGBoost Hyperparameter Grid Search
============================================================

Parameter grid:
  n_estimators: [100, 200, 300]
  max_depth: [3, 5, 7, 10]
  learning_rate: [0.01, 0.05, 0.1, 0.2]
  min_child_weight: [1, 3, 5]
  subsample: [0.6, 0.8, 1.0]
  colsample_bytree: [0.6, 0.8, 1.0]
  gamma: [0, 0.1, 0.2]

Total combinations: 3888

Starting grid search (this may take a while)...
Using 5-fold cross-validation with ROC AUC scoring

Fitting 5 folds for each of 3888 candidates, totalling 19440 fits
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=100, subsample=0.6; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=100, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=100, subsample=0.6; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=100, subsample=0.6; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=100, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=100, subsample=0.6; total time=   1.4s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=100, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=100, subsample=0.6; total time=   1.5s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=100, subsample=1.0; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=100, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=100, subsample=1.0; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=100, subsample=1.0; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=100, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=100, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=100, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=200, subsample=0.6; total time=   2.1s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=200, subsample=0.6; total time=   2.1s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=200, subsample=0.6; total time=   2.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=200, subsample=0.6; total time=   2.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=200, subsample=0.6; total time=   2.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=200, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=200, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=200, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=200, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=200, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=200, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=200, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=200, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=200, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=200, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=300, subsample=0.6; total time=   2.8s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=300, subsample=0.6; total time=   2.5s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=300, subsample=0.6; total time=   2.7s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=300, subsample=0.6; total time=   2.7s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=300, subsample=0.6; total time=   2.8s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=300, subsample=0.8; total time=   2.8s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=300, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=300, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=300, subsample=0.8; total time=   2.5s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=300, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=100, subsample=0.6; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=100, subsample=0.6; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=300, subsample=1.0; total time=   2.6s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=300, subsample=1.0; total time=   2.6s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=300, subsample=1.0; total time=   2.7s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=300, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=100, subsample=0.6; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=100, subsample=0.6; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=1, n_estimators=300, subsample=1.0; total time=   2.7s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=100, subsample=0.6; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=100, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=100, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=100, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=100, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=100, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=100, subsample=1.0; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=100, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=100, subsample=1.0; total time=   1.1s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=100, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=100, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, subsample=0.6; total time=   1.8s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, subsample=0.6; total time=   2.0s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, subsample=0.6; total time=   2.0s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, subsample=0.6; total time=   1.9s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, subsample=0.6; total time=   2.0s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=300, subsample=0.6; total time=   2.5s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=300, subsample=0.6; total time=   2.6s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=300, subsample=0.6; total time=   2.6s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=300, subsample=0.6; total time=   2.6s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   2.6s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=300, subsample=0.6; total time=   2.8s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   2.6s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   2.6s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=100, subsample=0.6; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=300, subsample=1.0; total time=   2.6s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=300, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   2.6s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=300, subsample=1.0; total time=   2.6s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=100, subsample=0.6; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=300, subsample=1.0; total time=   2.6s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=300, subsample=1.0; total time=   2.6s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=100, subsample=0.6; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=100, subsample=0.6; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=100, subsample=0.6; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=100, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=100, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=100, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=100, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=100, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=100, subsample=1.0; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=100, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=100, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=100, subsample=1.0; total time=   1.3s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=100, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=200, subsample=0.6; total time=   2.0s

/Users/danielyang/anaconda3/envs/prediction-trader/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=1, n_estimators=300, subsample=0.8; total time=  13.2s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=1, n_estimators=300, subsample=0.8; total time=   8.5s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=1, n_estimators=300, subsample=1.0; total time=   8.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=1, n_estimators=300, subsample=0.8; total time=   8.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=1, n_estimators=300, subsample=0.8; total time=  12.3s
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=100, subsample=0.6; total time=   3.1s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=1, n_estimators=300, subsample=1.0; total time=   8.1s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=100, subsample=0.6; total time=   4.1s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=100, subsample=0.6; total time=   4.0s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=1, n_estimators=300, subsample=1.0; total time=  11.5s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=100, subsample=0.6; total time=   3.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=100, subsample=0.8; total time=   3.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=1, n_estimators=300, subsample=1.0; total time=   8.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=100, subsample=0.8; total time=   4.5s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=100, subsample=0.8; total time=   4.2s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=1, n_estimators=300, subsample=1.0; total time=  10.7s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=100, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=100, subsample=0.8; total time=   4.4s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=100, subsample=1.0; total time=   3.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=100, subsample=0.6; total time=   4.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=100, subsample=1.0; total time=   3.4s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=100, subsample=1.0; total time=   4.8s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=100, subsample=1.0; total time=   4.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=100, subsample=1.0; total time=   4.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, subsample=0.6; total time=   4.8s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, subsample=0.6; total time=   4.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, subsample=0.6; total time=   4.8s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, subsample=0.6; total time=   6.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, subsample=0.6; total time=   6.8s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, subsample=0.8; total time=   5.0s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, subsample=0.8; total time=   7.0s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, subsample=0.8; total time=   5.5s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, subsample=0.8; total time=   7.0s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, subsample=0.8; total time=   7.1s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, subsample=1.0; total time=   5.2s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, subsample=1.0; total time=   7.4s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, subsample=1.0; total time=   7.0s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, subsample=1.0; total time=   5.1s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, subsample=1.0; total time=   7.0s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=300, subsample=0.6; total time=   6.7s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=300, subsample=0.6; total time=   8.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=300, subsample=0.6; total time=   8.8s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=300, subsample=0.6; total time=   9.0s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   6.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=300, subsample=0.6; total time=   9.2s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   9.6s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   6.8s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   9.6s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=100, subsample=0.6; total time=   3.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=300, subsample=1.0; total time=   6.8s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=300, subsample=1.0; total time=   9.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   9.7s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=300, subsample=1.0; total time=   9.6s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=100, subsample=0.6; total time=   3.8s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=100, subsample=0.6; total time=   2.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=100, subsample=0.6; total time=   2.8s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=300, subsample=1.0; total time=   9.4s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=100, subsample=0.6; total time=   4.0s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=300, subsample=1.0; total time=   9.7s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=100, subsample=0.8; total time=   4.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=100, subsample=0.8; total time=   4.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=100, subsample=0.8; total time=   3.2s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=100, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=100, subsample=0.8; total time=   4.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=100, subsample=1.0; total time=   4.6s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=100, subsample=1.0; total time=   4.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=100, subsample=1.0; total time=   4.5s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=100, subsample=1.0; total time=   4.2s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=100, subsample=1.0; total time=   4.2s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, subsample=0.6; total time=   4.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, subsample=0.6; total time=   4.5s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, subsample=0.6; total time=   6.1s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, subsample=0.6; total time=   5.8s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, subsample=0.8; total time=   4.5s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, subsample=0.8; total time=   4.6s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, subsample=0.6; total time=   6.1s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, subsample=0.8; total time=   6.2s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, subsample=0.8; total time=   6.1s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, subsample=0.8; total time=   6.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, subsample=1.0; total time=   6.5s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, subsample=1.0; total time=   4.7s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, subsample=1.0; total time=   4.7s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, subsample=1.0; total time=   6.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, subsample=1.0; total time=   6.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=300, subsample=0.6; total time=   8.1s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=300, subsample=0.6; total time=   8.2s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=300, subsample=0.6; total time=   8.1s
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=300, subsample=0.6; total time=   7.2s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=300, subsample=0.8; total time=   7.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=300, subsample=0.6; total time=   7.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=300, subsample=0.8; total time=   8.1s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=300, subsample=0.8; total time=   7.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=300, subsample=0.8; total time=   7.6s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=300, subsample=0.8; total time=   7.7s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=300, subsample=1.0; total time=   8.0s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=300, subsample=1.0; total time=   7.4s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=300, subsample=1.0; total time=   8.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=300, subsample=1.0; total time=   7.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=300, subsample=1.0; total time=   8.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=100, subsample=0.6; total time=  11.1s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=100, subsample=0.6; total time=  11.5s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=100, subsample=0.6; total time=  11.5s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=100, subsample=0.6; total time=  11.7s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=100, subsample=0.6; total time=  12.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=100, subsample=0.8; total time=  13.5s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=100, subsample=0.8; total time=  13.2s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=100, subsample=0.8; total time=  13.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=100, subsample=0.8; total time=  13.5s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=100, subsample=0.8; total time=  13.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=100, subsample=1.0; total time=  14.6s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=100, subsample=1.0; total time=  15.1s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=100, subsample=1.0; total time=  15.1s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=100, subsample=1.0; total time=  14.6s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=100, subsample=1.0; total time=  14.8s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=200, subsample=0.6; total time=  17.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=200, subsample=0.6; total time=  18.7s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=200, subsample=0.6; total time=  19.2s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=200, subsample=0.6; total time=  19.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=200, subsample=0.6; total time=  18.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=200, subsample=0.8; total time=  20.2s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=200, subsample=0.8; total time=  20.6s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=200, subsample=0.8; total time=  20.2s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=200, subsample=0.8; total time=  21.3s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=200, subsample=0.8; total time=  20.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=200, subsample=1.0; total time=  22.5s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=200, subsample=1.0; total time=  22.8s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=200, subsample=1.0; total time=  22.9s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=200, subsample=1.0; total time=  23.0s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.05, max_depth=10, min_child_weight=1, n_estimators=200, subsample=1.0; total time=  22.4s

                  feature  importance
43               home_eFG    0.065574
42               away_eFG    0.061563
23              home_FG3A    0.051310
36               home_PTS    0.044811
17               away_PTS    0.034148
3               away_FG3M    0.030044
4               away_FG3A    0.023905
81    home_10g_player_FGA    0.013969
22              home_FG3M    0.013088
19               home_FGM    0.012837
50    away_5g_player_FG3A    0.011257
12               away_AST    0.009818
92    away_10g_player_FTA    0.009386
46  away_5g_player_FG_PCT    0.008758
41            away_losses    0.008648
35                home_PF    0.008354
45     home_5g_player_FGA    0.008134
1                away_FGA    0.008029
31               home_AST    0.007930
85   home_10g_player_FG3M    0.007929
66     away_5g_player_AST    0.007659
14               away_BLK    0.007358
7                away_FTA    0.007339
21            home_FG_PCT    0.007320
0                away_FGM    0.007272

Top 10 Parameter Combinations by CV Score:

,params,mean_test_score,std_test_score,mean_train_score
1411,"{'colsample_bytree': 0.8, 'gamma': 0, 'learnin...",0.875717,0.005431,0.899255
1843,"{'colsample_bytree': 0.8, 'gamma': 0.1, 'learn...",0.875716,0.005429,0.899255
2275,"{'colsample_bytree': 0.8, 'gamma': 0.2, 'learn...",0.875693,0.005446,0.899228
2293,"{'colsample_bytree': 0.8, 'gamma': 0.2, 'learn...",0.875470,0.005580,0.898296
1861,"{'colsample_bytree': 0.8, 'gamma': 0.1, 'learn...",0.875423,0.005512,0.898256
1429,"{'colsample_bytree': 0.8, 'gamma': 0, 'learnin...",0.875421,0.005516,0.898245
1420,"{'colsample_bytree': 0.8, 'gamma': 0, 'learnin...",0.875420,0.005561,0.898763
1852,"{'colsample_bytree': 0.8, 'gamma': 0.1, 'learn...",0.875391,0.005516,0.898760
2284,"{'colsample_bytree': 0.8, 'gamma': 0.2, 'learn...",0.875391,0.005516,0.898759
2276,"{'colsample_bytree': 0.8, 'gamma': 0.2, 'learn...",0.875370,0.005004,0.897807

In [15]:
# Save the best model to nba/models
import os
import pickle
import json
from datetime import datetime

# Create models directory if it doesn't exist
os.makedirs("models", exist_ok=True)

# Save the best model using pickle
model_path = "models/xgboost_best_model.pkl"
with open(model_path, 'wb') as f:
    pickle.dump(best_xgb, f)
print(f"\n✓ Best model saved to {model_path}")

# Save best parameters and performance metrics
model_info = {
    "model_type": "XGBoost",
    "best_params": grid_search.best_params_,
    "cv_roc_auc": float(grid_search.best_score_),
    "holdout_metrics": {
        "accuracy": float(accuracy_score(y1_test, y_pred_best)),
        "precision": float(precision_score(y1_test, y_pred_best)),
        "recall": float(recall_score(y1_test, y_pred_best)),
        "f1": float(f1_score(y1_test, y_pred_best)),
        "roc_auc": float(roc_auc_score(y1_test, y_proba_best))
    },
    "training_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    "training_samples": len(X1_train),
    "test_samples": len(X1_test),
    "features": list(X1.columns)
}

info_path = "models/xgboost_best_model_info.json"
with open(info_path, 'w') as f:
    json.dump(model_info, f, indent=2)
print(f"✓ Model info saved to {info_path}")

# Also save feature importances
fi_path = "models/xgboost_feature_importances.csv"
fi_best.to_csv(fi_path, index=False)
print(f"✓ Feature importances saved to {fi_path}")

print(f"\nModel artifacts saved:")
print(f"  1. {model_path} - Trained model (pickle)")
print(f"  2. {info_path} - Model metadata (JSON)")
print(f"  3. {fi_path} - Feature importances (CSV)")

✓ Best model saved to models/xgboost_best_model.pkl
✓ Model info saved to models/xgboost_best_model_info.json
✓ Feature importances saved to models/xgboost_feature_importances.csv

Model artifacts saved:
  1. models/xgboost_best_model.pkl - Trained model (pickle)
  2. models/xgboost_best_model_info.json - Model metadata (JSON)
  3. models/xgboost_feature_importances.csv - Feature importances (CSV)

In [2]:
# Load training_games4.csv and run predictions through the best XGBoost model
import pickle
import json

# Load the saved model
with open("models/xgboost_best_model.pkl", "rb") as f:
    xgb_model = pickle.load(f)

# Load the model info to get the expected feature list
with open("models/xgboost_best_model_info.json", "r") as f:
    model_info = json.load(f)

feature_cols = model_info["features"]

# Load the new dataset
games4_df = pd.read_csv("data/training_games4.csv")
print(f"Loaded training_games4.csv: {games4_df.shape[0]} games, {games4_df.shape[1]} columns")

# Extract features in the same order the model was trained on
X_games4 = games4_df[feature_cols]

output_df = pd.DataFrame({
    "game_id": games4_df["game_id"],
    'game_date': games4_df['game_date'],
    'home_team': games4_df['home_team'],
    'away_team': games4_df['away_team'],
    'pred_prob': xgb_model.predict_proba(X_games4)[:, 1]
})

# Save the output to a CSV file
output_df.to_csv("data/games_predictions.csv", index=False)

output_df.head()

Loaded training_games4.csv: 28429 games, 121 columns

    game_id   game_date home_team away_team  pred_prob
0  20000058  2000-11-07       HOU       LAL   0.803786
1  20000060  2000-11-07       POR       ATL   0.045340
2  20000067  2000-11-08       DAL       MEM   0.093857
3  20000070  2000-11-08       LAC       UTA   0.146178
4  20000069  2000-11-08       DEN       MIN   0.356091